apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../bgd-base
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: yellow
  target:
    group: apps
    kind: Deployment
    name: bgd
    version: v1
